kind: Workflow
apiVersion: argoproj.io/v1alpha1
metadata:
  name: network-delay-chaos-workflow
  namespace: litmus
  creationTimestamp: null
  labels:
    cluster_id: aef0041c-aacb-4c92-a177-1ae8fad63aff
    subject: network-delay-chaos-workflow-litmus
    workflow_id: 0ef0e7ff-a61f-4b15-9ea6-89b63d7bcaa6
    workflows.argoproj.io/controller-instanceid: aef0041c-aacb-4c92-a177-1ae8fad63aff
spec:
  templates:
    - name: custom-chaos
      arguments: {}
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: install-chaos-experiments
            template: install-chaos-experiments
            arguments: {}
        - - name: pod-network-latency
            template: pod-network-latency
            arguments: {}
        - - name: revert-chaos
            template: revert-chaos
            arguments: {}
    - name: install-chaos-experiments
      arguments: {}
      inputs:
        artifacts:
          - name: pod-network-latency
            path: /tmp/pod-network-latency.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                description:
                  message: |
                    Injects network latency on pods belonging to an app deployment
                kind: ChaosExperiment

                metadata:
                  name: pod-network-latency
                  labels:
                    name: pod-network-latency
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: 1.13.6
                spec:
                  definition:
                    scope: Namespaced
                    permissions:
                      - apiGroups:
                          - ""
                          - batch
                          - apps
                          - apps.openshift.io
                          - argoproj.io
                          - litmuschaos.io
                        resources:
                          - jobs
                          - pods
                          - pods/log
                          - replicationcontrollers
                          - deployments
                          - statefulsets
                          - daemonsets
                          - replicasets
                          - deploymentconfigs
                          - rollouts
                          - pods/exec
                          - events
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                          - deletecollection
                    image: docker-dev.bin.pega.io/litmuschaos/go-runner:1.13.6
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name pod-network-latency
                    command:
                      - /bin/bash
                    env:
                      - name: TARGET_CONTAINER
                        value: ""
                      - name: NETWORK_INTERFACE
                        value: eth0
                      - name: LIB_IMAGE
                        value: docker-dev.bin.pega.io/litmuschaos/go-runner:1.13.6
                      - name: TC_IMAGE
                        value: gaiadocker/iproute2
                      - name: NETWORK_LATENCY
                        value: "2000"
                      - name: TOTAL_CHAOS_DURATION
                        value: "60"
                      - name: RAMP_TIME
                        value: ""
                      - name: LIB
                        value: litmus
                      - name: PODS_AFFECTED_PERC
                        value: ""
                      - name: TARGET_PODS
                        value: ""
                      - name: CONTAINER_RUNTIME
                        value: docker
                      - name: DESTINATION_IPS
                        value: ""
                      - name: DESTINATION_HOSTS
                        value: ""
                      - name: SOCKET_PATH
                        value: /var/run/docker.sock
                      - name: SEQUENCE
                        value: parallel
                    labels:
                      name: pod-network-latency
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/version: 1.13.6
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: docker-dev.bin.pega.io/litmuschaos/k8s:latest
        command:
          - sh
          - -c
        args:
          - kubectl apply -f /tmp/pod-network-latency.yaml -n
            {{workflow.parameters.adminModeNamespace}} |  sleep 30
        resources: {}
    - name: pod-network-latency
      arguments: {}
      inputs:
        artifacts:
          - name: pod-network-latency
            path: /tmp/chaosengine-pod-network-latency.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                kind: ChaosEngine

                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  generateName: pod-network-latency
                  labels:
                    instance_id: 761854f3-0424-4300-99a3-9153378388b7
                    context: litmus_pod_network_latency
                    workflow_name: network-delay-chaos-workflow
                spec:
                  jobCleanUpPolicy: retain
                  engineState: active
                  appinfo:
                    appns: blitzar
                    applabel: app.kubernetes.io/name=queue-service
                    appkind: deployment
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: pod-network-latency
                      spec:
                        components:
                          env:
                            - name: NETWORK_INTERFACE
                              value: eth0
                            - name: NETWORK_LATENCY
                              value: "2000"
                            - name: TOTAL_CHAOS_DURATION
                              value: "60"
                            - name: CONTAINER_RUNTIME
                              value: docker
                            - name: SOCKET_PATH
                              value: /var/run/docker.sock
                        probe:
                          - name: list-queue-details
                            type: httpProbe
                            mode: Edge
                            runProperties:
                              probeTimeout: 5
                              retry: 2
                              interval: 5
                              probePollingInterval: 1
                            httpProbe/inputs:
                              url: https://rupaa-491-f9mu9gvw-frontend-us-east-1.search.integration.pegaservice.net/qs/blitzar/v1/a684ac20-416c-4127-9386-846eb7dd0673/queues/testQueue01
                              insecureSkipVerify: true
                              responseTimeout: 1000
                              method:
                                get:
                                  criteria: ==
                                  responseCode: "200"
                  annotationCheck: "false"
      outputs: {}
      metadata:
        labels:
          weight: "10"
      container:
        name: ""
        image: docker-dev.bin.pega.io/litmuschaos/litmus-checker:latest
        args:
          - -file=/tmp/chaosengine-pod-network-latency.yaml
          - -saveName=/tmp/engine-name
        resources: {}
    - name: revert-chaos
      arguments: {}
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: docker-dev.bin.pega.io/litmuschaos/k8s:latest
        command:
          - sh
          - -c
        args:
          - "kubectl delete chaosengine -l 'instance_id in
            (761854f3-0424-4300-99a3-9153378388b7, )' -n
            {{workflow.parameters.adminModeNamespace}} "
        resources: {}
  entrypoint: custom-chaos
  arguments:
    parameters:
      - name: adminModeNamespace
        value: litmus
  serviceAccountName: argo-chaos
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
status:
  ? startedAt
  ? finishedAt
